Product landing page
Hasinarahman/product-landing-page pull request #1
Opened 2024-05-30 17:26 UTC by Hasinarahman

clone the repo in local machin.

2024-05-31 08:09 UTC, Hasinarahman commented
hello teacher @ahzamir
I done the product landing page project please check it and give me feedback.

2024-06-01 09:32 UTC, ahzamir requested changes
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although you have done a very great job by implementing some of the requirements, but still you need to work on your README.md file in order to get approval for your project
  - Check the inline comments below
  
# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.

![image](https://github.com/Hasinarahman/product-landing-page/assets/96838030/b86b6b91-dc53-4ed7-9a20-6ba44bb250e7)

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Product Landing Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
❌You have a professional README.md file in your project.

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-01 09:32 UTC, ahzamir commented on README.md
> +
- Remove this part

2024-06-01 09:32 UTC, ahzamir commented on README.md
> +![Demo](https://www.youtube.com/watch?v=37P87hQDxpk)
- Add your project as a demo (Screenshot)

2024-06-01 09:32 UTC, ahzamir commented on README.md
> +
- You need to add your LinkedIn account here

2024-06-02 14:38 UTC, Hasinarahman commented
hello sir @ahzamir 
I update the readme file please check it.

2024-06-04 18:11 UTC, Hasinarahman commented
@ahzamir 
Hi sir I am waiting for your feedback.

2024-06-05 19:53 UTC, ahzamir approved these changes
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Add some more design to your project so you can share it.

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Product Landing Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-06 04:57 UTC, Hasinarahman commented
ok Thanks you sir
@ahzamir

2024-06-06 04:57 UTC, merged